spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot_demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis:
  #config-locations: mybatis/mybatis-config.xml
#  mapper-locations: com/guxf/mapper/*.xml
#  type-aliases-package: com.example.demo.mapper.AuthorMapper